### ISSUE TITLE
Bug: local variable 'subclass' referenced before assignment

### ISSUE THREAD

**Issue by grvhi** [ethe/pygraphy#13]
```
ERROR:root:local variable 'subclass' referenced before assignment
Traceback (most recent call last):
  File "python3.7/site-packages/pygraphy/types/object.py", line 116, in _resolve
    returned = resolver(**kwargs)
  File "python3.7/site-packages/pygraphy/introspection.py", line 217, in possible_types
    t._type = subclass
UnboundLocalError: local variable 'subclass' referenced before assignment
```
Fix: change `subclass` to `member` [here](https://github.com/ethe/pygraphy/blob/master/pygraphy/introspection.py#L217)

**Comment by ethe** [comment]
Close by #14

**Comment by grvhi** [comment]
👍- glad I could help, even just a little!
