### ISSUE TITLE
Input Field doesn't work

### ISSUE THREAD

**Issue by chiaki64** [ethe/pygraphy#16]
When running the `examples/complex_example.py` code with FastAPI, and open the playground page, it will send `IntrospectionQuery` to server by default, then we can get an error response `{
  "error": "Response not successful: Received status code 400"
}`

the logger shows
```
INFO: ('127.0.0.1', 50915) - "POST / HTTP/1.1" 400
ERROR: 'str' object has no attribute 'name'
Traceback (most recent call last):
  File ".../virtualenvs/graphy-_XNMkQ0E/lib/python3.7/site-packages/pygraphy/types/object.py", line 116, in _resolve
    returned = resolver(**kwargs)
  File ".../virtualenvs/graphy-_XNMkQ0E/lib/python3.7/site-packages/pygraphy/introspection.py", line 233, in input_fields
    name=tfield.name,
AttributeError: 'str' object has no attribute 'name'
```

in  the [introspection.py](https://github.com/ethe/pygraphy/blob/master/pygraphy/introspection.py#L232-L236) file, we can see now the type of  `self.type.__fields__` there is `<class 'dict'>`, so the type of variable `tfield` is `<class 'str'>`, then we will get an AttributeError exception `AttributeError: 'str' object has no attribute 'name'`

```python
            for tfield in self.type.__fields__:
                print(self.type.__fields__, type(self.type.__fields__))
                # self.type.__fields__ = {'lat': Field(_obj=<class '__main__.GeoInput'>, name='lat', _ftype=<class 'float'>, description=None), ...}  <class 'dict'>
                values.append(InputValue(
                    name=tfield.name,
                    description=tfield.description,
                    default_value=None
                ))
```

it's easy to fix the problem, just call the values method

```python
# for tfield in self.type.__fields__:
for tfield in self.type.__fields__.values():
```

but now we get a new error

```python
INFO: ('127.0.0.1', 59413) - "POST / HTTP/1.1" 400
ERROR: __init__() got an unexpected keyword argument 'name'
Traceback (most recent call last):
  File ".../virtualenvs/graphy-_XNMkQ0E/lib/python3.7/site-packages/pygraphy/types/object.py", line 116, in _resolve
    returned = resolver(**kwargs)
  File ".../virtualenvs/graphy-_XNMkQ0E/lib/python3.7/site-packages/pygraphy/introspection.py", line 236, in input_fields
    default_value=None
TypeError: __init__() got an unexpected keyword argument 'name'
```

I have no idea for solving this problem now. Is this an unfinished feature or bug?

**Comment by ethe** [comment]
I am trying to reproduce it, thank you for reporting!

**Comment by ethe** [comment]
It does have a problem, I am working on fixing it.

**Comment by ethe** [comment]
I think it has already been fixed in #17, thanks.

**Comment by chiaki64** [comment]
Thanks for fix this problem, but it still seems to have some little problem.

Here is my test code, use the last complex_example code with FastAPI -> https://gist.github.com/chiaki64/e5168279926f0cadeacba59f78c5eb2c

and the query string in playground
```
# Query
query Address($geo: GeoInput!) {
  address(geo: $geo) {
    latlng
  }
}

# Variables
{
  "geo": {
    "lat": 1.0,
    "lng": 2.0
  }
}

# Response
{
  "error": {
    "errors": [
      {
        "message": "'dict' object has no attribute 'body'",
        "locations": null,
        "path": null
      }
    ],
    "data": {}
  }
}
```

The debug logger shows
```
ERROR: 'dict' object has no attribute 'body'
Traceback (most recent call last):
  File ".../virtualenvs/uta-D0zEo0Dl/lib/python3.7/site-packages/pygraphy/types/schema.py", line 185, in _execute_operation
    error_collector
  File ".../virtualenvs/uta-D0zEo0Dl/lib/python3.7/site-packages/pygraphy/types/object.py", line 113, in _resolve
    kwargs = self.__package_args(node, field, path)
  File ".../virtualenvs/uta-D0zEo0Dl/lib/python3.7/site-packages/pygraphy/types/object.py", line 261, in __package_args
    arg.value, slot
  File ".../virtualenvs/uta-D0zEo0Dl/lib/python3.7/site-packages/pygraphy/types/base.py", line 103, in load_literal_value
    node = parse_value(variables[name])
  File ".../virtualenvs/uta-D0zEo0Dl/lib/python3.7/site-packages/graphql/language/parser.py", line 120, in parse_value
    expect_token(lexer, TokenKind.SOF)
  File ".../virtualenvs/uta-D0zEo0Dl/lib/python3.7/site-packages/graphql/language/parser.py", line 1073, in expect_token
    lexer.advance()
  File ".../virtualenvs/uta-D0zEo0Dl/lib/python3.7/site-packages/graphql/language/lexer.py", line 85, in advance
    token = self.token = self.lookahead()
  File ".../virtualenvs/uta-D0zEo0Dl/lib/python3.7/site-packages/graphql/language/lexer.py", line 93, in lookahead
    token.next = self.read_token(token)
  File ".../virtualenvs/uta-D0zEo0Dl/lib/python3.7/site-packages/graphql/language/lexer.py", line 108, in read_token
    body = source.body
AttributeError: 'dict' object has no attribute 'body'
```

the `source` variable type there should be `<class 'graphql.language.source.Source'>`, but now we get the type ` <class 'dict'>`, so is this a  problem of graphql package or pygraphy package?

**Comment by ethe** [comment]
It's a little bit tricky, I am looking it.
