### ISSUE TITLE
The parse_value function makes mistake with type conversion

### ISSUE THREAD

**Issue by chiaki64** [ethe/pygraphy#21]
This is a topic extension with #18, in addition, I think the problem maybe caused by GraphQL-core-next package, but i am not sure.

```bash
$ python -V
Python 3.8.0
$ poetry show
pygraphy          0.1.8     A modern pythonic implementation of GraphQL.
graphql-core-next 1.1.1     GraphQL-core-next is a Python port of GraphQL.js, the JavaScript reference implementation for GraphQL.
```

I just change the scheme with GeoInput -> [gist](https://gist.github.com/chiaki64/049fb402d2f1bb46139daf60a9d874bf#file-test-py-L25)

```python
class GeoInput(pygraphy.Input):
    lat: float
    lng: float
    string: str  # new
```

the mutation works well in this usage
```
# Mutation
mutation createAddress{
  createAddress(geo: {
    lat: 1.0,
    lng: 2.0,
    string: "test"
  }) {
    latlng
  }
}

# Variables
{}

# Response
{
  "errors": null,
  "data": {
    "createAddress": {
      "latlng": "(1.0,2.0)"
    }
  }
}
```

but it doesn't work if i use query variables

```
# Mutation
mutation createAddress($geo: GeoInput!){
  createAddress(geo: $geo) {
    latlng
  }
}

# Variables
{
  "geo": {
    "lat": 123.01,
    "lng": 321.0,
    "string": "test"
  }
}

# Response
{
  "error": {
    "errors": [
      {
        "message": "type object 'str' has no attribute 'test'",
        "locations": null,
        "path": null
      }
    ],
    "data": {}
  }
}
```

the log shows

```
ERROR:    type object 'str' has no attribute 'test'
Traceback (most recent call last):
  File ".../.venv/lib/python3.8/site-packages/pygraphy/types/schema.py", line 183, in _execute_operation
    async for obj in await obj._resolve(
  File ".../.venv/lib/python3.8/site-packages/pygraphy/types/object.py", line 113, in _resolve
    kwargs = self.__package_args(node, field, path)
  File ".../.venv/lib/python3.8/site-packages/pygraphy/types/object.py", line 260, in __package_args
    kwargs[to_snake_case(arg.name.value)] = load_literal_value(
  File ".../.venv/lib/python3.8/site-packages/pygraphy/types/base.py", line 109, in load_literal_value
    return load_variable(variable, ptype)
  File ".../.venv/lib/python3.8/site-packages/pygraphy/types/base.py", line 115, in load_variable
    return ptype(**{key: load_variable(value, ptype.__fields__[key].ftype) for key, value in variable.items()})
  File ".../.venv/lib/python3.8/site-packages/pygraphy/types/base.py", line 115, in <dictcomp>
    return ptype(**{key: load_variable(value, ptype.__fields__[key].ftype) for key, value in variable.items()})
  File ".../.venv/lib/python3.8/site-packages/pygraphy/types/base.py", line 120, in load_variable
    return load_literal_value(node, ptype)
  File ".../.venv/lib/python3.8/site-packages/pygraphy/types/base.py", line 89, in load_literal_value
    value = getattr(ptype, node.value)
AttributeError: type object 'str' has no attribute 'test'
```

The error happens here -> https://github.com/ethe/pygraphy/blob/master/pygraphy/types/base.py#L119 ,
i add a new line to print variable `node` here,
```python
def load_variable(variable, ptype):
    if isinstance(ptype, types.InputType):
        return ptype(**{key: load_variable(value, ptype.__fields__[key].ftype) for key, value in variable.items()})
    elif is_list(ptype):
        return [load_variable(i, ptype.__args__[0]) for i in variable]
    else:
        node = parse_value(str(variable))
        print(node)  # new
        return load_literal_value(node, ptype)
```

i got three node types there

```
FloatValueNode at 0:6
IntValueNode at 0:3
EnumValueNode at 0:4  # it should be StringValueType
```

This is why i got the exception `AttributeError: type object 'str' has no attribute 'test'`, because the real node type there is not enum, the `parse_value` function is the culprit, it return an error node types.

So the question is whether my writing has gone wrong or is it not considered in the code?

**Comment by ethe** [comment]
I think it is my mistake, change the line
```python
node = parse_value(str(variable))
```
to
```python
parse_value(json.dumps(variable))
```
it can return the correct type, cause single quotes is not a valid mark to JSON string.

**Comment by chiaki64** [comment]
Oh, right, it is working now  :P

**Comment by ethe** [comment]
I am considering removing the dependency on GraphQL Core parser, it makes lower performance in the current. However, rewrite a parser is a heavy job because the grammar of GraphQL is complex.

**Comment by chiaki64** [comment]
Yes, this is a heavy but great job, and the benefits of refactoring may not be too high. The GraphQL-core-next library released a new version 3.0-beta, and it looks like a slight improvement in performance, maybe you can try it first. If you decide to refactor the code, I think I can provide some help, although the compilation principle is a bit difficult for me~

**Comment by ethe** [comment]
I think we can simply remove parse_value like https://github.com/ethe/pygraphy/pull/22, thank you for your support, I think maybe I can gift you a cup of coffee for thanks.

**Comment by ethe** [comment]
Fixed.
